version: "3.9"

volumes:
  postgres_db:
    driver: local

services:
  database:
    image: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    ports:
      - '9100:9100'
    environment:
      KC_DB_URL_HOST: database
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_FRONTEND_URL: http://localhost:9100/auth
      KC_HTTP_PORT: 9100
      KC_METRICS_ENABLED: 'true'
      KC_LOG_CONSOLE_COLOR: 'true'
      KC_HEALTH_ENABLED: 'true'
    depends_on:
      - database
    command:
      - start-dev
