name: CI
on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          java-version: 11
          maven-version: 3.9.0
      - name: Build jar
        run: mvn package
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: target-keycloak-mailchimp
          path: target/keycloak-mailchimp-*.jar

