name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: target-keycloak-mailchimp

      # Upload as an artifact of the current workflow
      - name: Upload build zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: Release artifacts
          path: '*.jar'

      # Make official GitHub release which will trigger
      # sending the mail with link for access
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '*.jar'
          draft: false
          prerelease: false
          allowUpdates: true
          bodyFile: CHANGELOG.md
          tag: v1.1.0
